// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9Hbyd6NG6RiFgOlvTPXQRt49zHa-OPc',
    appId: '1:585513886224:web:c56d250e7103c13d3ba095',
    messagingSenderId: '585513886224',
    projectId: 'chat-app-e65e4',
    authDomain: 'chat-app-e65e4.firebaseapp.com',
    storageBucket: 'chat-app-e65e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZ_qetb68ZjIZsX0tBMIgAICbLGSNbwk',
    appId: '1:585513886224:android:12662fd8fc7620453ba095',
    messagingSenderId: '585513886224',
    projectId: 'chat-app-e65e4',
    storageBucket: 'chat-app-e65e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FVXBddt12jjv_PrBTMdSgWPHPJl41Yk',
    appId: '1:585513886224:ios:29ea1cd4e332c62b3ba095',
    messagingSenderId: '585513886224',
    projectId: 'chat-app-e65e4',
    storageBucket: 'chat-app-e65e4.appspot.com',
    iosBundleId: 'com.khalafawy.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_FVXBddt12jjv_PrBTMdSgWPHPJl41Yk',
    appId: '1:585513886224:ios:41c5479e600ab7333ba095',
    messagingSenderId: '585513886224',
    projectId: 'chat-app-e65e4',
    storageBucket: 'chat-app-e65e4.appspot.com',
    iosBundleId: 'com.khalafawy.chatApp.RunnerTests',
  );
}
